spring.application.name=springboot_vms

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/spring_api_vms
spring.datasource.username=${DB_USERNAME:root}
# Cerca la variabile d'ambiente DB_PASSWORD. Se non la trova, lascia vuoto.
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration per Hibernate e JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate